In [47]:
import pandas as pd

In [48]:
celeb_dict = [
    {
        'Name': 'Kerry Washington',
        'Sex': 'Female',
        'Age': 43,
        'Height(ft)': 5.4,
        'Weight(lbs)': 117.0,
        'Zodiac Sign': 'Aquarius',
        'Tattoo Body Art': 'No'
    },

    {
        'Name': 'Jensen Ackles',
        'Sex': 'Male',
        'Age': 42,
        'Height(ft)': 6.1,
        'Weight(lbs)': 183.0,
        'Zodiac Sign': 'Pisces',
        'Tattoo Body Art': 'No'
    },

    {
        'Name': 'Shay Mitchell ',
        'Sex': 'Female',
        'Age': 33,
        'Height(ft)': 5.7,
        'Weight(lbs)': 132.0,
        'Zodiac Sign': 'Aries',
        'Tattoo Body Art': 'No'
    },

    {
        'Name': 'Ian Somerhalder',
        'Sex': 'Male',
        'Age': 41,
        'Height(ft)': 5.9,
        'Weight(lbs)': 165.5,
        'Zodiac Sign': 'Sagittarius',
        'Tattoo Body Art': 'No'
    },

    {
        'Name': 'Alycia Debnam-Carey',
        'Sex': 'Female',
        'Age': 27,
        'Height(ft)': 5.7,
        'Weight(lbs)': 121.0,
        'Zodiac Sign': 'Cancer',
        'Tattoo Body Art': 'No'
    },

    {
        'Name': 'Ryan Gosling',
        'Sex': 'Male',
        'Age': 40,
        'Height(ft)': 6.0,
        'Weight(lbs)': 172.0,
        'Zodiac Sign': 'Scorpio',
        'Tattoo Body Art': 'No'
    },

    {
        'Name': 'Ruby Rose',
        'Sex': 'Female',
        'Age': 34,
        'Height(ft)': 5.7,
        'Weight(lbs)': 170.0,
        'Zodiac Sign': 'Pisces',
        'Tattoo Body Art': 'No'
    },

    {
        'Name': 'Ashton Kutcher',
        'Sex': 'MAle',
        'Age': 42,
        'Height(ft)': 6.2, 
        'Weight(lbs)': 176.0,
        'Zodiac Sign': 'Aquarius',
        'Tattoo Body Art': 'No'
    },

    {
        'Name': 'Kate Upton',
        'Sex': 'Female',
        'Age': 28,
        'Height(ft)': 5.10,
        'Weight(lbs)': 156.5,
        'Zodiac Sign': 'Gemini',
        'Tattoo Body Art': 'Yes'
    },

    {
        'Name': 'Ricky Whittle',
        'Sex': 'Male',
        'Age': 38,
        'Height(ft)': 6.1,
        'Weight(lbs)': 200.5,
        'Zodiac Sign': 'Capricorn',
        'Tattoo Body Art': 'No'
    },

    {
        'Name': 'Jessica Biel',
        'Sex': 'Female',
        'Age': 38,
        'Height(ft)': 5.7,
        'Weight(lbs)': 121.0,
        'Zodiac Sign': 'Pisces',
        'Tattoo Body Art': 'No'
    },

    {
        'Name': 'Jason Momoa',
        'Sex': 'male',
        'Age': 41,
        'Height(ft)': 6.4,
        'Weight(lbs)': 234.0,
        'Zodiac Sign': 'Leo',
        'Tattoo Body Art': 'Yes'
    },

    {
        'Name': 'Marie Avgeropoulos',
        'Sex': 'Female',
        'Age': 34,
        'Height(ft)': 5.5,
        'Weight(lbs)': 121.0, 
        'Zodiac Sign': ' Gemini',
        'Tattoo Body Art': 'No'
    },

    {
        'Name': 'Stephen Amell',
        'Sex': 'Male',
        'Age': 39,
        'Height(ft)': 6.1,
        'Weight(lbs)': 182.0,
        'Zodiac Sign': 'Taurus',
        'Tattoo Body Art': 'No'
    },

    {
        'Name': 'Kate Hudson',
        'Sex': 'Female',
        'Age': 41,
        'Height(ft)': 5.6,
        'Weight(lbs)': 121.0,
        'Zodiac Sign': 'Aries',
        'Tattoo Body Art': 'No'
    },

    {
        'Name': 'Chace Crawford',
        'Sex': 'Male',
        'Age': 35,
        'Height(ft)': 6.0,
        'Weight(lbs)': 175.0,
        'Zodiac Sign': 'Cancer',
        'Tattoo Body Art': 'No'
    },

    {
        'Name': 'Olivia Wilde',
        'Sex': 'Female',
        'Age': 36,
        'Height(ft)': 5.7,
        'Weight(lbs)': 115.0,
        'Zodiac Sign': 'Pisces',
        'Tattoo Body Art': 'No'
    },

    {
        'Name': 'Michael Fassbender',
        'Sex': 'Male',
        'Age': 43,
        'Height(ft)': 6.0, 
        'Weight(lbs)': 174.0,
        'Zodiac Sign': 'Aries',
        'Tattoo Body Art': 'No'
    },

    {
        'Name': 'Daisy Ridley',
        'Sex': 'Female',
        'Age': 28,
        'Height(ft)': 5.7,
        'Weight(lbs)': 121.0,
        'Zodiac Sign': 'Aries',
        'Tattoo Body Art': 'No'
    },

    {
        'Name': 'Chris Pine',
        'Sex': 'Male',
        'Age': 40,
        'Height(ft)': 6.0,
        'Weight(lbs)': 172.0,
        'Zodiac Sign': 'Virgo',
        'Tattoo Body Art': 'No'
    },

    {
        'Name': 'Cate Blanchett',
        'Sex': 'Female',
        'Age': 51,
        'Height(ft)': 5.8,
        'Weight(lbs)': 130.0,
        'Zodiac Sign': 'Taurus',
        'Tattoo Body Art': 'No'
    },

    {
        'Name': 'Gerard Butler',
        'Sex': 'Male',
        'Age': 51,
        'Height(ft)': 6.2,
        'Weight(lbs)': 187.5,
        'Zodiac Sign': 'Scorpio',
        'Tattoo Body Art': 'No'
    },

    {
        'Name': 'Emma Watson',
        'Sex': 'Female',
        'Age': 30, 
        'Height(ft)': 5.5,
        'Weight(lbs)': 117.0,
        'Zodiac Sign': 'Aries',
        'Tattoo Body Art': 'No'
    },

    {
        'Name': 'Luke Evans',
        'Sex': 'Male',
        'Age': 41,
        'Height(ft)': 6.0,
        'Weight(lbs)': 174.0,
        'Zodiac Sign': 'Aries',
        'Tattoo Body Art': 'No'
    },

    {
        'Name': 'Penélope Cruz',
        'Sex': 'Female',
        'Age': 46,
        'Height(ft)': 5.6,
        'Weight(lbs)': 137.0,
        'Zodiac Sign': 'Taurus',
        'Tattoo Body Art': 'No'
    }

]

celeb_df = pd.DataFrame.from_dict(celeb_dict)  
celeb_df

,Name,Sex,Age,Height(ft),Weight(lbs),Zodiac Sign,Tattoo Body Art
0,Kerry Washington,Female,43,5.4,117.0,Aquarius,No
1,Jensen Ackles,Male,42,6.1,183.0,Pisces,No
2,Shay Mitchell,Female,33,5.7,132.0,Aries,No
3,Ian Somerhalder,Male,41,5.9,165.5,Sagittarius,No
4,Alycia Debnam-Carey,Female,27,5.7,121.0,Cancer,No
5,Ryan Gosling,Male,40,6.0,172.0,Scorpio,No
6,Ruby Rose,Female,34,5.7,170.0,Pisces,No
7,Ashton Kutcher,MAle,42,6.2,176.0,Aquarius,No
8,Kate Upton,Female,28,5.1,156.5,Gemini,Yes
9,Ricky Whittle,Male,38,6.1,200.5,Capricorn,No
10,Jessica Biel,Female,38,5.7,121.0,Pisces,No
11,Jason Momoa,male,41,6.4,234.0,Leo,Yes
12,Marie Avgeropoulos,Female,34,5.5,121.0,Gemini,No
13,Stephen Amell,Male,39,6.1,182.0,Taurus,No
14,Kate Hudson,Female,41,5.6,121.0,Aries,No
15,Chace Crawford,Male,35,6.0,175.0,Cancer,No
16,Olivia Wilde,Female,36,5.7,115.0,Pisces,No
17,Michael Fassbender,Male,43,6.0,174.0,Aries,No
18,Daisy Ridley,Female,28,5.7,121.0,Aries,No
19,Chris Pine,Male,40,6.0,172.0,Virgo,No
20,Cate Blanchett,Female,51,5.8,130.0,Taurus,No
21,Gerard Butler,Male,51,6.2,187.5,Scorpio,No
22,Emma Watson,Female,30,5.5,117.0,Aries,No
23,Luke Evans,Male,41,6.0,174.0,Aries,No
24,Penélope Cruz,Female,46,5.6,137.0,Taurus,No